// Code generated by hertz generator.

package main

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "tiktok/cmd/api/biz/handler"
	"tiktok/cmd/api/biz/handler/api"
	"tiktok/pkg/errno"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.NoRoute(func(ctx context.Context, c *app.RequestContext) { // used for HTTP 404
		api.SendResponse(c, errno.ServiceErr)
	})
	r.NoMethod(func(ctx context.Context, c *app.RequestContext) { // used for HTTP 405
		api.SendResponse(c, errno.ServiceErr)
	})
}
