// Code generated by hertz generator.

package api

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/form3tech-oss/jwt-go"
	"net/http"
	"strconv"
	api "tiktok/cmd/api/biz/model/api"
	"tiktok/cmd/api/biz/mw"
	"tiktok/cmd/api/biz/rpc"
	"tiktok/kitex_gen/user"
	"tiktok/pkg/consts"
	"tiktok/pkg/errno"
)

// Register .
// @router /douyin/user/register/ [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err))
		return
	}
	//注册，获取id
	_, err = rpc.CreateUser(context.Background(), &user.RegisterReq{
		Username: req.Username,
		Password: req.Password,
	})
	if err != nil {
		SendResponse(c, errno.ConvertErr(err))
		return
	}

	//登录
	mw.JwtMiddleware.LoginHandler(ctx, c)
}

// Login .
// @router /douyin/user/login/ [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	mw.JwtMiddleware.LoginHandler(ctx, c)
}

// UserInfo .
// @router /douyin/user/ [GET]
func UserInfo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.UserInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err))
		return
	}

	//解析token，获取请求者的id
	tokenString := req.Token
	claims := jwt.MapClaims{}
	_, err = jwt.ParseWithClaims(tokenString, claims, func(token *jwt.Token) (interface{}, error) {
		return []byte(consts.SecretKey), nil
	})
	var requestUserId interface{}
	for key, val := range claims {
		if key == "user_id" {
			requestUserId = val
			break
		}
	}
	var resp *user.UserInfoResp
	resp, err = rpc.GetUserInfo(context.Background(), &user.UserInfoReq{
		UserId: req.UserID,
		Token:  strconv.FormatFloat(requestUserId.(float64), 'f', -1, 64),
	})

	/*
			处理返回值，json格式：
		{
		    "status_code": 0,
		    "status_msg": "string",
		    "user": {
		        "id": 0,
		        "name": "string",
		        "follow_count": 0,
		        "follower_count": 0,
		        "is_follow": true
		    }
		}
	*/
	c.JSON(http.StatusOK, utils.H{
		"status_code": 0,
		"status_msg":  "success",
		"user":        resp.User,
	})
}

// VideoStream .
// @router /douyin/feed/ [GET]
func VideoStream(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.VideoStreamReq
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err))
		return
	}

	resp := new(api.VideoStreamResp)

	c.JSON(0, resp)
}

// VideoUpload .
// @router /douyin/publish/action/ [POST]
func VideoUpload(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.VideoUploadReq
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err))
		return
	}

	resp := new(api.VideoUploadResp)

	c.JSON(0, resp)
}

// VideoList .
// @router /douyin/publish/list/ [GET]
func VideoList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.VideoListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err))
		return
	}

	resp := new(api.VideoListResp)

	c.JSON(0, resp)
}

// LikeAction .
// @router /douyin/favorite/action/ [POST]
func LikeAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.LikeActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err))
		return
	}

	resp := new(api.LikeActionResp)

	c.JSON(0, resp)
}

// LikeList .
// @router /douyin/favorite/list/ [GET]
func LikeList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.LikeListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err))
		return
	}

	resp := new(api.LikeListResp)

	c.JSON(0, resp)
}

// CommentAction .
// @router /douyin/comment/action/ [POST]
func CommentAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CommentActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err))
		return
	}

	resp := new(api.CommentActionResp)

	c.JSON(0, resp)
}

// CommentList .
// @router /douyin/comment/list/ [GET]
func CommentList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.CommentListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err))
		return
	}

	resp := new(api.CommentListResp)

	c.JSON(0, resp)
}

// FollowAction .
// @router /douyin/relation/action/ [POST]
func FollowAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FollowActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err))
		return
	}

	resp := new(api.FollowActionResp)

	c.JSON(0, resp)
}

// FollowList .
// @router /douyin/relation/follow/list/ [GET]
func FollowList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FollowListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err))
		return
	}

	resp := new(api.FollowListResp)

	c.JSON(0, resp)
}

// FollowerList .
// @router /douyin/relation/follower/list/ [GET]
func FollowerList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FollowerListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err))
		return
	}

	resp := new(api.FollowerListResp)

	c.JSON(0, resp)
}

// FriendList .
// @router /douyin/relation/friend/list/ [GET]
func FriendList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.FriendListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err))
		return
	}

	resp := new(api.FriendListResp)

	c.JSON(0, resp)
}

// MessageChat .
// @router /douyin/message/chat/ [GET]
func MessageChat(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.MessageChatReq
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err))
		return
	}

	resp := new(api.MessageChatResp)

	c.JSON(0, resp)
}

// MessageAction .
// @router /douyin/message/action/ [POST]
func MessageAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.MessageActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		SendResponse(c, errno.ConvertErr(err))
		return
	}

	resp := new(api.MessageActionResp)

	c.JSON(0, resp)
}
